set -e

ZCLOUD_PROV=AWS
ZCLOUD_AWS_KEY_ID=$AWS_ACCESS_KEY_ID
ZCLOUD_AWS_SECRET_KEY=$AWS_SECRET_ACCESS_KEY
ZCLOUD_AWS_REGION="us-east-1"

echo "TESTING AWS"

./end-to-end-tests.sh

echo "PASSED end-to-end testing with AWS"
